CREATE TABLE `updated` (
  `ID` int unsigned NOT NULL AUTO_INCREMENT,
  `Title` varchar(2000) DEFAULT '',
  `VolumeInfo` varchar(100) DEFAULT '',
  `Series` varchar(300) DEFAULT '',
  `Periodical` varchar(200) DEFAULT '',
  `Author` varchar(1000) DEFAULT '',
  `Year` varchar(14) DEFAULT '',
  `Edition` varchar(60) DEFAULT '',
  `Publisher` varchar(400) DEFAULT '',
  `City` varchar(100) DEFAULT '',
  `Pages` varchar(100) DEFAULT '',
  `PagesInFile` int unsigned NOT NULL DEFAULT '0',
  `Language` varchar(150) DEFAULT '',
  `Topic` varchar(500) DEFAULT '',
  `Library` varchar(50) DEFAULT '',
  `Issue` varchar(100) DEFAULT '',
  `Identifier` varchar(300) DEFAULT '',
  `ISSN` varchar(9) DEFAULT '',
  `ASIN` varchar(200) DEFAULT '',
  `UDC` varchar(200) DEFAULT '',
  `LBC` varchar(200) DEFAULT '',
  `DDC` varchar(45) DEFAULT '',
  `LCC` varchar(45) DEFAULT '',
  `Doi` varchar(45) DEFAULT '',
  `Googlebookid` varchar(45) DEFAULT '',
  `OpenLibraryID` varchar(200) DEFAULT '',
  `Commentary` varchar(10000) DEFAULT '',
  `DPI` int unsigned DEFAULT '0',
  `Color` varchar(1) DEFAULT '',
  `Cleaned` varchar(1) DEFAULT '',
  `Orientation` varchar(1) DEFAULT '',
  `Paginated` varchar(1) DEFAULT '',
  `Scanned` varchar(1) DEFAULT '',
  `Bookmarked` varchar(1) DEFAULT '',
  `Searchable` varchar(1) DEFAULT '',
  `Filesize` bigint unsigned NOT NULL DEFAULT '0',
  `Extension` varchar(50) DEFAULT '',
  `MD5` char(32) DEFAULT '',
  `Generic` char(32) DEFAULT '',
  `Visible` char(3) DEFAULT '',
  `Locator` varchar(733) DEFAULT '',
  `Local` int unsigned DEFAULT '0',
  `TimeAdded` timestamp NOT NULL DEFAULT '2000-01-01 05:00:00',
  `TimeLastModified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Coverurl` varchar(200) DEFAULT '',
  `Tags` varchar(500) DEFAULT '',
  `IdentifierWODash` varchar(300) DEFAULT '',
  PRIMARY KEY (`ID`),
  KEY `DOI_INDEX` (`Doi`),
  KEY `Extension` (`Extension`),
  KEY `Generic` (`Generic`),
  KEY `Identifier` (`Identifier`),
  KEY `Language` (`Language`),
  UNIQUE KEY `MD5` (`MD5`),
  KEY `TimeAdded` (`TimeAdded`),
  KEY `TimeLastModifiedID` (`TimeLastModified`,`ID`),
  KEY `Topic` (`Topic`(3)),
  KEY `VisibleID` (`Visible`,`ID`),
  KEY `VisibleTimeAdded` (`Visible`,`TimeAdded`),
  KEY `VisibleTimeLastModified` (`Visible`,`TimeLastModified`,`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci
